name: API Tests

on:
  workflow_dispatch:

jobs:
  cypress-api:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Root Dependencies
        run: npm install

      - name: Install Project Dependencies
        run: npm run install:all

      - name: Run API Tests
        uses: cypress-io/github-action@v6
        with:
          # Inicia apenas o backend para os testes de API
          start: npm run start:backend
          # Aguarda o backend responder com 200 OK na rota do swagger
          wait-on: 'http://localhost:3001/api/docs/openapi.json'
          # Roda apenas os specs de API
          spec: cypress/e2e/api/**/*.cy.js
